### PR TITLE
AR callback for Destroy

### PR DESCRIPTION
**Pull request by leeacto**
@bellycard/platform

### CODE REVIEW

**Comment by shaqq** [comment]
^^ hound lulz

**Comment by shaqq** [comment]
+1

**Comment by shaqq** [comment]
@leeacto do we still need this?

also, pretty happy hound is gone. that stuff was a nightmare.

**Comment by leeacto** [comment]
I don't recall the context, but I would assume it should be added. thoughts?

**Comment by shaqq** [comment]
+1. A lot of times we depend on `acts_as_paranoid`, so we wouldn't actually delete records. Though it makes to have this.

**Comment by hstrowd** [comment]
:+1:

**Pull request merged**
